apiVersion: v1
kind: Pod
metadata:
  labels:
    app: test
    service: db
  name: db
  namespace: test
spec:
  containers:
    - env:
        - name: MYSQL_DATABASE
          value: test
        - name: MYSQL_ROOT_PASSWORD
          value: P@ssw0rd
      image: mysql
      name: db
      args:
        - "--default-authentication-plugin"
        - mysql_native_password
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: db-dir
          mountPath: /var/lib/mysql
  volumes:
    - name: db-dir
      hostPath:
        # Ensure the file directory is created.
        path: /k8s-volumes/data2
        type: DirectoryOrCreate
