apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: test
    service: db
  name: db
  namespace: test
spec:
  selector:
    matchLabels:
      app: test
      service: db
  serviceName: "test-db"
  replicas: 1
  template:
    metadata:
      labels:
        app: test
        service: db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: test
            - name: MYSQL_ROOT_PASSWORD
              value: P@ssw0rd
          image: mysql
          name: db
          args:
            - "--default-authentication-plugin"
            - mysql_native_password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: test-db-data-pv-volume
              mountPath: /var/lib/mysql
      volumes:
        - name: test-db-data-pv-volume
          persistentVolumeClaim:
            claimName: test-db-data-pvc
