# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    secrets:
      - mysql-user
      - mysql-password
    env_file:
      - production.env
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - backend

  #  adminer:
  #    image: adminer
  #    ports:
  #      - 8080:8080
  #    networks:
  #      - frontend
  #      - backend

  # api:
  #   image: checklist-api:latest
  #   deploy:
  #     replicas: 3
  #   ports:
  #     - 8000:8000
  #   secrets:
  #     - mysql-user
  #     - mysql-password
  #   environment:
  #     - CHECKLIST_DB_IPADDRESS=transactions.mysql.checklist.local
  #     - CHECKLIST_DB_PORT=3306
  #   networks:
  #     - frontend
  #     - backend

  # ui:
  #   image: checklist-ui:prod
  #   deploy:
  #     replicas: 3
  #   ports:
  #     - 80:80
  #   networks:
  #     - frontend

#  sms:
#    image: checklist-sms:latest
#    networks:
#      - frontend

volumes:
  checklist-data:

networks:
  frontend:
  backend:

secrets:
  mysql-user:
    file: ./mysql_user.txt
  mysql-password:
    file: ./mysql_password.txt
