apiVersion: v1
kind: Service
metadata:
  name: mongo-rs0
  labels:
    app: mongo-rs0
spec:
  ports:
    - name: mongo-rs0
      port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: mongo-rs0
