---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: checklist
    service: kafkaApp
  name: kafka-repcon
  namespace: checklist
spec:
  replicas: 1
  selector:
    app: checklist
    service: kafkaApp
  template:
    metadata:
      labels:
        app: checklist
        service: kafkaApp
    spec:
      containers:
        - name: zk1
          # - command:
          #     - zookeeper-server-start.sh
          #     - /config/zookeeper.properties
          image: "wurstmeister/kafka"
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zk-s:2181"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            - name: KAFKA_ADVERTISED_LISTENERS
              value: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
            - name: KAFKA_LISTENERS
              value: INSIDE://:9092,OUTSIDE://:9094
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: INSIDE
