apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: checklist
    service: kafka
  name: kafka
  namespace: checklist
spec:
  selector:
    matchLabels:
      app: checklist
      service: kafka
  serviceName: "checklist-kafka"
  replicas: 1
  template:
    metadata:
      labels:
        app: checklist
        service: kafka
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: kafka
          image: wurstmeister/kafka:latest
          ports:
            - containerPort: 9094
          # volumeMounts:
          #   - name: checklist-kafka-volume
          #     mountPath: /var/run/docker.sock
          env:
            - name: HOSTNAME_COMMAND
              value: "docker info | grep ^Name: | cut -d' ' -f 2"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zoo1:2181"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            - name: KAFKA_ADVERTISED_LISTENERS
              value: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
            - name: KAFKA_LISTENERS
              value: INSIDE://:9092,OUTSIDE://:9094
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: INSIDE
  volumeClaimTemplates:
    - metadata:
        name: checklist-kafka-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
