apiVersion: v1
kind: Service
metadata:
  name: zk-s
  namespace: checklist
  labels:
    app: checklist
    service: zk-1
spec:
  ports:
    - name: client
      port: 2181
      protocol: TCP
    - name: follower
      port: 2888
      protocol: TCP
    - name: leader
      port: 3888
      protocol: TCP
  selector:
    app: checklist
    service: zk-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zk-deployment-1
  namespace: checklist
  labels:
    app: checklist
    service: zk-deployment-1
spec:
  selector:
    matchLabels:
      app: checklist
      service: zk-1
  template:
    metadata:
      labels:
        app: checklist
        service: zk-1
    spec:
      containers:
        - name: zk1
          #          image: bitnami/zookeeper
          image: zookeeper
          ports:
            - containerPort: 2181
            - containerPort: 2888
            - containerPort: 3888
            - containerPort: 8080
          env:
            #            - name: ZOOKEEPER_ID
            #              value: "1"
            #            - name: ZOOKEEPER_SERVER_1
            #              value: zk1
            #            - name: ALLOW_ANONYMOUS_LOGIN
            #              value: "yes"
            - name: ZOO_MY_ID
              value: "1"
            - name: ZOO_SERVERS
              value: "server.1=0.0.0.0:2888:3888;2181" # server.2=zoo2:2888:3888;2181"

