apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongos
spec:
  selector:
    matchLabels:
      app: mongos
  replicas: 3
  template:
    metadata:
      labels:
        app: mongos
    spec:
      containers:
        - name: mongos
          image: mongo
          command:
            - mongos
            - "--configdb"
            - cfgrs/mongo-cfgsvr-0.mongo-cfgsvr:27017,mongo-cfgsvr-0.mongo-cfgsvr:27017,mongo-cfgsvr-0.mongo-cfgsvr:27017
            - "--bind_ip_all"
            - "--port"
            - "27017"
          ports:
            - containerPort: 27017
