apiVersion: v1
kind: Service
metadata:
  name: mongo-shard1
  labels:
    app: mongo-shard1
spec:
  ports:
    - name: mongo-shard1
      port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: mongo-shard1
