apiVersion: v1
kind: Service
metadata:
  name: mongo-shard2
  labels:
    app: mongo-shard2
spec:
  ports:
    - name: mongo-shard2
      port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: mongo-shard2
